# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d19202c30712a25677b0bb5df35c3a3450baca1dfe9a61a30889b043ef7859928735d717fb680a272e889616a559c15604f8b62742cdb56e48f33ae058869316

test:
  secret_key_base: cd24fe85380f2534898928fdfdb55b325a5106f410c10e25e97e004ada40843a050cfde6ffdcc8e60f559e2fc9da142529fda02cd97f9f30d14be410f39977be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
